-- AlterTable
ALTER TABLE "Wheel" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Wheel" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Wheel" ADD COLUMN IF NOT EXISTS "colorPrimary" TEXT NOT NULL DEFAULT '#5c0a14';
ALTER TABLE "Wheel" ADD COLUMN IF NOT EXISTS "colorSecondary" TEXT NOT NULL DEFAULT '#0a0a0a';
ALTER TABLE "Wheel" ADD COLUMN IF NOT EXISTS "colorAccent" TEXT NOT NULL DEFAULT '#c9a24d';
ALTER TABLE "Wheel" ADD COLUMN IF NOT EXISTS "hubImageUrl" TEXT;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Wheel_userId_isActive_idx" ON "Wheel"("userId", "isActive");
