-- AlterTable
ALTER TABLE "Wheel" ADD COLUMN "celebrateEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Wheel" ADD COLUMN "spinVolume" INTEGER NOT NULL DEFAULT 80;
ALTER TABLE "Wheel" ADD COLUMN "celebrateVolume" INTEGER NOT NULL DEFAULT 95;
